window.PHRASES = [
  { pt: "Olá", en: "Hello" },
  { pt: "Bom dia", en: "Good morning" },
  { pt: "Boa tarde", en: "Good afternoon" },
  { pt: "Boa noite", en: "Good evening / Good night" },
  { pt: "Como está?", en: "How are you?" },
  { pt: "Tudo bem?", en: "All good?" },
  { pt: "Estou bem", en: "I am well" },
  { pt: "E você?", en: "And you?" },
  { pt: "Muito bem", en: "Very well" },
  { pt: "Mais ou menos", en: "So-so" },

  { pt: "Por favor", en: "Please" },
  { pt: "Obrigado", en: "Thank you (male)" },
  { pt: "Obrigada", en: "Thank you (female)" },
  { pt: "De nada", en: "You're welcome" },
  { pt: "Com licença", en: "Excuse me" },
  { pt: "Desculpa", en: "Sorry" },
  { pt: "Não faz mal", en: "No problem" },
  { pt: "Peço desculpa", en: "I apologize" },
  { pt: "Claro", en: "Of course" },
  { pt: "Sem problema", en: "No problem" },

  { pt: "Sim", en: "Yes" },
  { pt: "Não", en: "No" },
  { pt: "Talvez", en: "Maybe" },
  { pt: "Acho que sim", en: "I think so" },
  { pt: "Acho que não", en: "I don't think so" },

  { pt: "Não entendo", en: "I don't understand" },
  { pt: "Entendo", en: "I understand" },
  { pt: "Pode repetir?", en: "Can you repeat?" },
  { pt: "Mais devagar, por favor", en: "Slower, please" },
  { pt: "Fala inglês?", en: "Do you speak English?" },

  { pt: "Quanto custa?", en: "How much does it cost?" },
  { pt: "É caro", en: "It's expensive" },
  { pt: "É barato", en: "It's cheap" },
  { pt: "Quero isto", en: "I want this" },
  { pt: "Só estou a ver", en: "Just looking" },

  { pt: "Onde é a casa de banho?", en: "Where is the bathroom?" },
  { pt: "Onde fica isto?", en: "Where is this?" },
  { pt: "Perto", en: "Near" },
  { pt: "Longe", en: "Far" },
  { pt: "À direita", en: "To the right" },
  { pt: "À esquerda", en: "To the left" },

  { pt: "Tenho fome", en: "I am hungry" },
  { pt: "Tenho sede", en: "I am thirsty" },
  { pt: "Vamos comer", en: "Let's eat" },
  { pt: "O cardápio, por favor", en: "The menu, please" },
  { pt: "A conta, por favor", en: "The bill, please" },

  { pt: "Que horas são?", en: "What time is it?" },
  { pt: "Agora", en: "Now" },
  { pt: "Hoje", en: "Today" },
  { pt: "Amanhã", en: "Tomorrow" },
  { pt: "Ontem", en: "Yesterday" },

  { pt: "Preciso de ajuda", en: "I need help" },
  { pt: "Está bem", en: "Okay" },
  { pt: "Tudo certo", en: "All set" },
  { pt: "Boa sorte", en: "Good luck" },
  { pt: "Até logo", en: "See you later" },
  { pt: "Até amanhã", en: "See you tomorrow" },
  { pt: "Tchau", en: "Bye" },
  { pt: "Bem-vindo", en: "Welcome" }
];
