const phrases = [
  { portuguese: "Olá", english: "Hello" },
  { portuguese: "Bom dia", english: "Good morning" },
  { portuguese: "Boa tarde", english: "Good afternoon" },
  { portuguese: "Boa noite", english: "Good evening / Good night" },
  { portuguese: "Tudo bem?", english: "How are you?" },
  { portuguese: "Como estás?", english: "How are you?" },
  { portuguese: "Estou bem", english: "I am well" },
  { portuguese: "E tu?", english: "And you?" },
  { portuguese: "Muito obrigado", english: "Thank you very much" },
  { portuguese: "Obrigada", english: "Thank you (female speaker)" },

  { portuguese: "De nada", english: "You're welcome" },
  { portuguese: "Por favor", english: "Please" },
  { portuguese: "Com licença", english: "Excuse me" },
  { portuguese: "Desculpa", english: "Sorry" },
  { portuguese: "Não faz mal", english: "No problem" },
  { portuguese: "Sim", english: "Yes" },
  { portuguese: "Não", english: "No" },
  { portuguese: "Talvez", english: "Maybe" },
  { portuguese: "Claro", english: "Of course" },
  { portuguese: "Está bem", english: "Okay" },

  { portuguese: "Não percebo", english: "I don't understand" },
  { portuguese: "Percebo", english: "I understand" },
  { portuguese: "Pode repetir?", english: "Can you repeat?" },
  { portuguese: "Fala inglês?", english: "Do you speak English?" },
  { portuguese: "Não falo português", english: "I don't speak Portuguese" },
  { portuguese: "Falo um pouco de português", english: "I speak a little Portuguese" },
  { portuguese: "Como se diz...?", english: "How do you say...?" },
  { portuguese: "O que é isto?", english: "What is this?" },
  { portuguese: "Quanto custa?", english: "How much does it cost?" },
  { portuguese: "Onde fica a casa de banho?", english: "Where is the bathroom?" },

  { portuguese: "Onde fica?", english: "Where is it?" },
  { portuguese: "Aqui", english: "Here" },
  { portuguese: "Ali", english: "There" },
  { portuguese: "Agora", english: "Now" },
  { portuguese: "Depois", english: "Later" },
  { portuguese: "Hoje", english: "Today" },
  { portuguese: "Amanhã", english: "Tomorrow" },
  { portuguese: "Ontem", english: "Yesterday" },
  { portuguese: "Sempre", english: "Always" },
  { portuguese: "Nunca", english: "Never" },

  { portuguese: "Talvez mais tarde", english: "Maybe later" },
  { portuguese: "Estou cansado", english: "I am tired (male)" },
  { portuguese: "Estou cansada", english: "I am tired (female)" },
  { portuguese: "Tenho fome", english: "I am hungry" },
  { portuguese: "Tenho sede", english: "I am thirsty" },
  { portuguese: "Vamos!", english: "Let's go!" },
  { portuguese: "Até logo", english: "See you later" },
  { portuguese: "Até amanhã", english: "See you tomorrow" },
  { portuguese: "Boa sorte", english: "Good luck" },
  { portuguese: "Parabéns", english: "Congratulations" },

  { portuguese: "Ajuda!", english: "Help!" },
  { portuguese: "Está aberto?", english: "Is it open?" },
  { portuguese: "Está fechado?", english: "Is it closed?" },
  { portuguese: "Quero isto", english: "I want this" },
  { portuguese: "Quero isso", english: "I want that" },
  { portuguese: "Gosto disto", english: "I like this" },
  { portuguese: "Não gosto disto", english: "I don't like this" },
  { portuguese: "É muito bom", english: "It is very good" },
  { portuguese: "É mau", english: "It is bad" },
  { portuguese: "Está bem assim", english: "It's fine like this" },

  { portuguese: "Preciso de ajuda", english: "I need help" },
  { portuguese: "Tenho uma pergunta", english: "I have a question" },
  { portuguese: "Um momento, por favor", english: "One moment, please" },
  { portuguese: "Sem problema", english: "No problem" },
  { portuguese: "Com certeza", english: "Certainly" },
  { portuguese: "Desculpe", english: "Excuse me (formal)" },
  { portuguese: "Bom trabalho", english: "Good job" },
  { portuguese: "Divirta-se", english: "Have fun" },
  { portuguese: "Bem-vindo", english: "Welcome" },
  { portuguese: "Bem-vinda", english: "Welcome (female)" }
];
