window.VOCABULARY = {
  transportation: [
    { pt: "carro", en: "car" },
    { pt: "ônibus", en: "bus" },
    { pt: "trem", en: "train" },
    { pt: "metrô", en: "subway" },
    { pt: "avião", en: "airplane" },
    { pt: "bicicleta", en: "bicycle" },
    { pt: "motocicleta", en: "motorcycle" },
    { pt: "navio", en: "ship" },
    { pt: "barco", en: "boat" },
    { pt: "táxi", en: "taxi" },
    { pt: "caminhão", en: "truck" },
    { pt: "estrada", en: "road" },
    { pt: "rua", en: "street" },
    { pt: "avenida", en: "avenue" },
    { pt: "ponte", en: "bridge" },
    { pt: "estação", en: "station" },
    { pt: "aeroporto", en: "airport" },
    { pt: "porto", en: "port" },
    { pt: "bilhete", en: "ticket" },
    { pt: "mapa", en: "map" },
    { pt: "trânsito", en: "traffic" },
    { pt: "sinal", en: "signal" },
    { pt: "parada", en: "stop" },
    { pt: "garagem", en: "garage" },
    { pt: "volante", en: "steering wheel" },
    { pt: "freio", en: "brake" },
    { pt: "motor", en: "engine" },
    { pt: "passageiro", en: "passenger" },
    { pt: "condutor", en: "driver" },
    { pt: "viagem", en: "trip" }
  ],

  foods: [
    { pt: "pão", en: "bread" },
    { pt: "arroz", en: "rice" },
    { pt: "feijão", en: "beans" },
    { pt: "carne", en: "meat" },
    { pt: "frango", en: "chicken" },
    { pt: "peixe", en: "fish" },
    { pt: "ovo", en: "egg" },
    { pt: "leite", en: "milk" },
    { pt: "queijo", en: "cheese" },
    { pt: "manteiga", en: "butter" },
    { pt: "açúcar", en: "sugar" },
    { pt: "sal", en: "salt" },
    { pt: "óleo", en: "oil" },
    { pt: "água", en: "water" },
    { pt: "suco", en: "juice" },
    { pt: "café", en: "coffee" },
    { pt: "chá", en: "tea" },
    { pt: "cerveja", en: "beer" },
    { pt: "vinho", en: "wine" },
    { pt: "bolo", en: "cake" },
    { pt: "sopa", en: "soup" },
    { pt: "salada", en: "salad" },
    { pt: "massa", en: "pasta" },
    { pt: "pizza", en: "pizza" },
    { pt: "hambúrguer", en: "hamburger" },
    { pt: "batata", en: "potato" },
    { pt: "tomate", en: "tomato" },
    { pt: "cebola", en: "onion" },
    { pt: "alho", en: "garlic" },
    { pt: "banana", en: "banana" },
    { pt: "maçã", en: "apple" },
    { pt: "laranja", en: "orange" },
    { pt: "uva", en: "grape" },
    { pt: "morango", en: "strawberry" },
    { pt: "abacaxi", en: "pineapple" },
    { pt: "manga", en: "mango" },
    { pt: "melancia", en: "watermelon" },
    { pt: "limão", en: "lemon" },
    { pt: "iogurte", en: "yogurt" },
    { pt: "chocolate", en: "chocolate" },
    { pt: "biscoito", en: "cookie" },
    { pt: "sanduíche", en: "sandwich" },
    { pt: "cereal", en: "cereal" },
    { pt: "mel", en: "honey" },
    { pt: "azeite", en: "olive oil" },
    { pt: "molho", en: "sauce" },
    { pt: "sobremesa", en: "dessert" },
    { pt: "refeição", en: "meal" }
  ],

  numbers: Array.from({ length: 100 }, (_, i) => ({
    pt: String(i + 1),
    en: String(i + 1)
  })),

  colors: [
    { pt: "vermelho", en: "red" },
    { pt: "azul", en: "blue" },
    { pt: "verde", en: "green" },
    { pt: "amarelo", en: "yellow" },
    { pt: "preto", en: "black" },
    { pt: "branco", en: "white" },
    { pt: "cinza", en: "gray" },
    { pt: "marrom", en: "brown" },
    { pt: "roxo", en: "purple" },
    { pt: "rosa", en: "pink" },
    { pt: "laranja", en: "orange" },
    { pt: "bege", en: "beige" },
    { pt: "azul claro", en: "light blue" },
    { pt: "azul escuro", en: "dark blue" },
    { pt: "verde claro", en: "light green" },
    { pt: "verde escuro", en: "dark green" },
    { pt: "vermelho claro", en: "light red" },
    { pt: "vermelho escuro", en: "dark red" },
    { pt: "amarelo claro", en: "light yellow" },
    { pt: "amarelo escuro", en: "dark yellow" },
    { pt: "rosa claro", en: "light pink" },
    { pt: "rosa escuro", en: "dark pink" },
    { pt: "cinza claro", en: "light gray" },
    { pt: "cinza escuro", en: "dark gray" },
    { pt: "marrom claro", en: "light brown" },
    { pt: "marrom escuro", en: "dark brown" },
    { pt: "turquesa", en: "turquoise" },
    { pt: "violeta", en: "violet" },
    { pt: "índigo", en: "indigo" },
    { pt: "preto fosco", en: "matte black" }
  ],

  clothing: [
    { pt: "camisa", en: "shirt" },
    { pt: "camiseta", en: "t-shirt" },
    { pt: "calça", en: "pants" },
    { pt: "shorts", en: "shorts" },
    { pt: "saia", en: "skirt" },
    { pt: "vestido", en: "dress" },
    { pt: "jaqueta", en: "jacket" },
    { pt: "casaco", en: "coat" },
    { pt: "blusa", en: "blouse" },
    { pt: "meias", en: "socks" },
    { pt: "sapatos", en: "shoes" },
    { pt: "tênis", en: "sneakers" },
    { pt: "sandálias", en: "sandals" },
    { pt: "botas", en: "boots" },
    { pt: "chapéu", en: "hat" },
    { pt: "boné", en: "cap" },
    { pt: "luvas", en: "gloves" },
    { pt: "cinto", en: "belt" },
    { pt: "gravata", en: "tie" },
    { pt: "pijama", en: "pajamas" }
  ],

  everyday: [
    { pt: "porta", en: "door" },
    { pt: "janela", en: "window" },
    { pt: "mesa", en: "table" },
    { pt: "cadeira", en: "chair" },
    { pt: "cama", en: "bed" },
    { pt: "sofá", en: "sofa" },
    { pt: "chave", en: "key" },
    { pt: "telefone", en: "phone" },
    { pt: "relógio", en: "watch" },
    { pt: "computador", en: "computer" },
    { pt: "papel", en: "paper" },
    { pt: "caneta", en: "pen" },
    { pt: "livro", en: "book" },
    { pt: "bolsa", en: "bag" },
    { pt: "mochila", en: "backpack" },
    { pt: "carteira", en: "wallet" },
    { pt: "dinheiro", en: "money" },
    { pt: "cartão", en: "card" },
    { pt: "luz", en: "light" },
    { pt: "tomada", en: "outlet" },
    { pt: "banheiro", en: "bathroom" },
    { pt: "cozinha", en: "kitchen" },
    { pt: "quarto", en: "bedroom" },
    { pt: "sala", en: "living room" },
    { pt: "escada", en: "stairs" },
    { pt: "espelho", en: "mirror" },
    { pt: "toalha", en: "towel" },
    { pt: "sabão", en: "soap" },
    { pt: "lixo", en: "trash" },
    { pt: "calendário", en: "calendar" }
  ],

  animals: [
    { pt: "cão", en: "dog" },
    { pt: "gato", en: "cat" },
    { pt: "pássaro", en: "bird" },
    { pt: "peixe", en: "fish" },
    { pt: "cavalo", en: "horse" },
    { pt: "vaca", en: "cow" },
    { pt: "porco", en: "pig" },
    { pt: "ovelha", en: "sheep" },
    { pt: "cabra", en: "goat" },
    { pt: "galinha", en: "chicken" },
    { pt: "pato", en: "duck" },
    { pt: "coelho", en: "rabbit" },
    { pt: "rato", en: "mouse" },
    { pt: "leão", en: "lion" },
    { pt: "tigre", en: "tiger" },
    { pt: "elefante", en: "elephant" },
    { pt: "girafa", en: "giraffe" },
    { pt: "zebra", en: "zebra" },
    { pt: "urso", en: "bear" },
    { pt: "macaco", en: "monkey" },
    { pt: "lobo", en: "wolf" },
    { pt: "raposa", en: "fox" },
    { pt: "veado", en: "deer" },
    { pt: "cobra", en: "snake" },
    { pt: "lagarto", en: "lizard" },
    { pt: "sapo", en: "frog" },
    { pt: "tartaruga", en: "turtle" },
    { pt: "crocodilo", en: "crocodile" },
    { pt: "tubarão", en: "shark" },
    { pt: "golfinho", en: "dolphin" },
    { pt: "baleia", en: "whale" },
    { pt: "foca", en: "seal" },
    { pt: "polvo", en: "octopus" },
    { pt: "caranguejo", en: "crab" },
    { pt: "abelha", en: "bee" },
    { pt: "borboleta", en: "butterfly" },
    { pt: "formiga", en: "ant" },
    { pt: "aranha", en: "spider" },
    { pt: "mosca", en: "fly" },
    { pt: "mosquito", en: "mosquito" },
    { pt: "besouro", en: "beetle" },
    { pt: "camelo", en: "camel" },
    { pt: "rinoceronte", en: "rhinoceros" },
    { pt: "hipopótamo", en: "hippopotamus" },
    { pt: "pinguim", en: "penguin" },
    { pt: "águia", en: "eagle" },
    { pt: "coruja", en: "owl" },
    { pt: "papagaio", en: "parrot" }
  ]
};
