const vocabulary = {

  transportation: [
    { pt: "carro", en: "car" },
    { pt: "autocarro", en: "bus" },
    { pt: "comboio", en: "train" },
    { pt: "metro", en: "subway" },
    { pt: "avião", en: "airplane" },
    { pt: "bicicleta", en: "bicycle" },
    { pt: "moto", en: "motorcycle" },
    { pt: "táxi", en: "taxi" },
    { pt: "navio", en: "ship" },
    { pt: "barco", en: "boat" },
    { pt: "camião", en: "truck" },
    { pt: "ambulância", en: "ambulance" },
    { pt: "eléctrico", en: "tram" },
    { pt: "ferry", en: "ferry" },
    { pt: "helicóptero", en: "helicopter" },
    { pt: "patinete", en: "scooter" },
    { pt: "estrada", en: "road" },
    { pt: "rua", en: "street" },
    { pt: "ponte", en: "bridge" },
    { pt: "túnel", en: "tunnel" },
    { pt: "paragem", en: "stop" },
    { pt: "estação", en: "station" },
    { pt: "bilhete", en: "ticket" },
    { pt: "trânsito", en: "traffic" },
    { pt: "engarrafamento", en: "traffic jam" },
    { pt: "passadeira", en: "crosswalk" },
    { pt: "semáforo", en: "traffic light" },
    { pt: "estacionamento", en: "parking" },
    { pt: "garagem", en: "garage" },
    { pt: "viagem", en: "trip" }
  ],

  foods: [
    { pt: "pão", en: "bread" },
    { pt: "arroz", en: "rice" },
    { pt: "massa", en: "pasta" },
    { pt: "carne", en: "meat" },
    { pt: "frango", en: "chicken" },
    { pt: "peixe", en: "fish" },
    { pt: "ovo", en: "egg" },
    { pt: "queijo", en: "cheese" },
    { pt: "leite", en: "milk" },
    { pt: "manteiga", en: "butter" },
    { pt: "iogurte", en: "yogurt" },
    { pt: "sopa", en: "soup" },
    { pt: "salada", en: "salad" },
    { pt: "batata", en: "potato" },
    { pt: "tomate", en: "tomato" },
    { pt: "alface", en: "lettuce" },
    { pt: "cenoura", en: "carrot" },
    { pt: "cebola", en: "onion" },
    { pt: "alho", en: "garlic" },
    { pt: "maçã", en: "apple" },
    { pt: "banana", en: "banana" },
    { pt: "laranja", en: "orange" },
    { pt: "pera", en: "pear" },
    { pt: "uva", en: "grape" },
    { pt: "morango", en: "strawberry" },
    { pt: "limão", en: "lemon" },
    { pt: "açúcar", en: "sugar" },
    { pt: "sal", en: "salt" },
    { pt: "pimenta", en: "pepper" },
    { pt: "azeite", en: "olive oil" },
    { pt: "óleo", en: "oil" },
    { pt: "vinagre", en: "vinegar" },
    { pt: "bolo", en: "cake" },
    { pt: "chocolate", en: "chocolate" },
    { pt: "doce", en: "dessert" },
    { pt: "gelado", en: "ice cream" },
    { pt: "biscoito", en: "cookie" },
    { pt: "café", en: "coffee" },
    { pt: "chá", en: "tea" },
    { pt: "água", en: "water" },
    { pt: "sumo", en: "juice" },
    { pt: "cerveja", en: "beer" },
    { pt: "vinho", en: "wine" },
    { pt: "pequeno-almoço", en: "breakfast" },
    { pt: "almoço", en: "lunch" },
    { pt: "jantar", en: "dinner" },
    { pt: "lanche", en: "snack" },
    { pt: "sobremesa", en: "dessert" }
  ],

  numbers: Array.from({ length: 100 }, (_, i) => ({
    pt: [
      "zero","um","dois","três","quatro","cinco","seis","sete","oito","nove",
      "dez","onze","doze","treze","catorze","quinze","dezasseis","dezassete","dezoito","dezanove",
      "vinte","vinte e um","vinte e dois","vinte e três","vinte e quatro","vinte e cinco","vinte e seis","vinte e sete","vinte e oito","vinte e nove",
      "trinta","trinta e um","trinta e dois","trinta e três","trinta e quatro","trinta e cinco","trinta e seis","trinta e sete","trinta e oito","trinta e nove",
      "quarenta","quarenta e um","quarenta e dois","quarenta e três","quarenta e quatro","quarenta e cinco","quarenta e seis","quarenta e sete","quarenta e oito","quarenta e nove",
      "cinquenta","cinquenta e um","cinquenta e dois","cinquenta e três","cinquenta e quatro","cinquenta e cinco","cinquenta e seis","cinquenta e sete","cinquenta e oito","cinquenta e nove",
      "sessenta","sessenta e um","sessenta e dois","sessenta e três","sessenta e quatro","sessenta e cinco","sessenta e seis","sessenta e sete","sessenta e oito","sessenta e nove",
      "setenta","setenta e um","setenta e dois","setenta e três","setenta e quatro","setenta e cinco","setenta e seis","setenta e sete","setenta e oito","setenta e nove",
      "oitenta","oitenta e um","oitenta e dois","oitenta e três","oitenta e quatro","oitenta e cinco","oitenta e seis","oitenta e sete","oitenta e oito","oitenta e nove",
      "noventa","noventa e um","noventa e dois","noventa e três","noventa e quatro","noventa e cinco","noventa e seis","noventa e sete","noventa e oito","noventa e nove"
    ][i],
    en: String(i)
  })),

  colors: [
    { pt: "branco", en: "white" },
    { pt: "preto", en: "black" },
    { pt: "cinzento", en: "gray" },
    { pt: "cinzento claro", en: "light gray" },
    { pt: "cinzento escuro", en: "dark gray" },
    { pt: "vermelho", en: "red" },
    { pt: "vermelho claro", en: "light red" },
    { pt: "vermelho escuro", en: "dark red" },
    { pt: "azul", en: "blue" },
    { pt: "azul claro", en: "light blue" },
    { pt: "azul escuro", en: "dark blue" },
    { pt: "verde", en: "green" },
    { pt: "verde claro", en: "light green" },
    { pt: "verde escuro", en: "dark green" },
    { pt: "amarelo", en: "yellow" },
    { pt: "amarelo claro", en: "light yellow" },
    { pt: "amarelo escuro", en: "dark yellow" },
    { pt: "laranja", en: "orange" },
    { pt: "rosa", en: "pink" },
    { pt: "roxo", en: "purple" },
    { pt: "castanho", en: "brown" },
    { pt: "bege", en: "beige" },
    { pt: "dourado", en: "gold" },
    { pt: "prateado", en: "silver" },
    { pt: "turquesa", en: "turquoise" },
    { pt: "bordô", en: "burgundy" },
    { pt: "cor-de-rosa claro", en: "light pink" },
    { pt: "cor-de-rosa escuro", en: "dark pink" },
    { pt: "azul-marinho", en: "navy blue" },
    { pt: "verde-água", en: "teal" }
  ],

  clothing: [
    { pt: "camisa", en: "shirt" },
    { pt: "t-shirt", en: "t-shirt" },
    { pt: "calças", en: "pants" },
    { pt: "calções", en: "shorts" },
    { pt: "casaco", en: "jacket" },
    { pt: "camisola", en: "sweater" },
    { pt: "vestido", en: "dress" },
    { pt: "saia", en: "skirt" },
    { pt: "sapatos", en: "shoes" },
    { pt: "ténis", en: "sneakers" },
    { pt: "botas", en: "boots" },
    { pt: "meias", en: "socks" },
    { pt: "chapéu", en: "hat" },
    { pt: "boné", en: "cap" },
    { pt: "cachecol", en: "scarf" },
    { pt: "luvas", en: "gloves" },
    { pt: "cinto", en: "belt" },
    { pt: "relógio", en: "watch" },
    { pt: "óculos", en: "glasses" },
    { pt: "pijama", en: "pajamas" }
  ],

  everyday: [
    { pt: "casa", en: "house" },
    { pt: "quarto", en: "room" },
    { pt: "porta", en: "door" },
    { pt: "janela", en: "window" },
    { pt: "mesa", en: "table" },
    { pt: "cadeira", en: "chair" },
    { pt: "cama", en: "bed" },
    { pt: "luz", en: "light" },
    { pt: "chave", en: "key" },
    { pt: "telefone", en: "phone" },
    { pt: "computador", en: "computer" },
    { pt: "livro", en: "book" },
    { pt: "caneta", en: "pen" },
    { pt: "papel", en: "paper" },
    { pt: "mochila", en: "backpack" },
    { pt: "garrafa", en: "bottle" },
    { pt: "copos", en: "cups" },
    { pt: "prato", en: "plate" },
    { pt: "talheres", en: "cutlery" },
    { pt: "relógio de parede", en: "wall clock" },
    { pt: "espelho", en: "mirror" },
    { pt: "sabão", en: "soap" },
    { pt: "toalha", en: "towel" },
    { pt: "escova", en: "brush" },
    { pt: "pasta de dentes", en: "toothpaste" },
    { pt: "caderno", en: "notebook" },
    { pt: "carregador", en: "charger" },
    { pt: "lixo", en: "trash" },
    { pt: "saco", en: "bag" },
    { pt: "caixa", en: "box" }
  ],

  animals: [
    { pt: "cão", en: "dog" },
    { pt: "gato", en: "cat" },
    { pt: "pássaro", en: "bird" },
    { pt: "peixe", en: "fish" },
    { pt: "cavalo", en: "horse" },
    { pt: "vaca", en: "cow" },
    { pt: "porco", en: "pig" },
    { pt: "ovelha", en: "sheep" },
    { pt: "cabra", en: "goat" },
    { pt: "galinha", en: "chicken" },
    { pt: "pato", en: "duck" },
    { pt: "coelho", en: "rabbit" },
    { pt: "rato", en: "mouse" },
    { pt: "leão", en: "lion" },
    { pt: "tigre", en: "tiger" },
    { pt: "urso", en: "bear" },
    { pt: "lobo", en: "wolf" },
    { pt: "raposa", en: "fox" },
    { pt: "veado", en: "deer" },
    { pt: "macaco", en: "monkey" },
    { pt: "elefante", en: "elephant" },
    { pt: "girafa", en: "giraffe" },
    { pt: "zebra", en: "zebra" },
    { pt: "rinoceronte", en: "rhinoceros" },
    { pt: "hipopótamo", en: "hippopotamus" },
    { pt: "crocodilo", en: "crocodile" },
    { pt: "cobra", en: "snake" },
    { pt: "lagarto", en: "lizard" },
    { pt: "aranha", en: "spider" },
    { pt: "abelha", en: "bee" },
    { pt: "borboleta", en: "butterfly" },
    { pt: "formiga", en: "ant" },
    { pt: "mosca", en: "fly" },
    { pt: "mosquito", en: "mosquito" },
    { pt: "tubarão", en: "shark" },
    { pt: "baleia", en: "whale" },
    { pt: "golfinho", en: "dolphin" },
    { pt: "polvo", en: "octopus" },
    { pt: "caranguejo", en: "crab" },
    { pt: "lagosta", en: "lobster" },
    { pt: "camelo", en: "camel" },
    { pt: "burro", en: "donkey" },
    { pt: "hamster", en: "hamster" },
    { pt: "porquinho-da-índia", en: "guinea pig" },
    { pt: "papagaio", en: "parrot" },
    { pt: "coruja", en: "owl" },
    { pt: "pinguim", en: "penguin" },
    { pt: "foca", en: "seal" }
  ]

};
